---
title: 异常处理
date: 2020-12-16 19:44:18
permalink: /pages/e0f63b/
categories: 
  - 后端
  - Java入门基础
  - 异常处理
tags: 
  - thorws关键字
  - thorw关键字
  - try关键字
  - catch关键字
  - finally关键字
---
## 异常概述

在使用计算机语言进行项目开发的过程中，即使程序员把代码写得尽善尽美，在系统的运行过程中仍然会遇到一些问题，因为很多问题不是靠代码能够避免的，比如：客户输入数据的格式，读取文件是否存在，网络是否始终保持通畅等等。

**异常：在Java语言中，将程序执行中发生的不正常情况称为“异常”。(开发过程中的语法错误和逻辑错误不是异常)。**

> Java程序在执行过程中所发生的异常事件可分为两类：

- `Error`：Java虚拟机无法解决的严重问题。如：JVM系统内部错误、资源耗尽等严重情况。比如：`StackOverflowError`和`OOM`。一般不编写针对性的代码进行处理。
- `Exception`:其它因编程错误或偶然的外在因素导致的一般性问题，可以使用针对性的代码进行处理。例如
  - 空指针访问
  - 试图读取不存在的文件
  - 网络连接中断
  - 数组角标越界



> 解决方法

对于这些错误，一般有两种解决方法：

一是遇到错误就终止程序的运行。

另一种方法是由程序员在编写程序时，就考虑到错误的检测、错误消息的提示，以及错误的处理。

捕获错误最理想的是在**编译期间**，但有的错误只有在运行时才会发生。比如：除数为0，数组下标越界等



> 异常体系架构

![image-20201216211904145](https://raw.githubusercontent.com/SaulJWu/images/main/20201216211904.png)



异常又分为：编译时异常（`checked`）和运行时异常（`unchecked`）。

> 运行时异常

- 是指编译器不要求强制处置的异常。一般是指编程时的逻辑错误，是程序员应该积极避免其出现的异常。`java.lang.RuntimeException`类及它的子类都是运行时异常。
- 对于这类异常，可以不作处理，因为这类异常很普遍，若全处理可能会对程序的可读性和运行效率产生影响。



> 编译时异常

- 是指编译器要求必须处置的异常。即程序在运行时由于外界因素造成的一般性异常。**编译器要求Java程序必须捕获或声明所有编译时异常。**
- 对于这类异常，如果程序不处理，可能会带来意想不到的结果。



## 常见异常

> 编译时异常

- `java.io.IOExeption`
  - `FileNotFoundException`
  - `EOFException`
- `java.lang.ClassNotFoundException`

> 运行时异常

- `java.lang.RuntimeException`
  - `ClassCastException`
  - `ArrayIndexOutOfBoundsException`
  - `NullPointerException`
  - `ArithmeticException` 算术异常
  - `NumberFormatException`
  - `InputMismatchException`
  - `……`
- `java.lang.InterruptedException`
- `java.io.FileNotFoundException`
- `java.sql.SQLException`

## 异常处理

在编写程序时，经常要在可能出现错误的地方加上检测的代码，如进行x/y运算时，要**检测分母为0，数据为空，输入的不是数据而是字符**等。过多的if-else分支会导致程序的代码加长、臃肿，可读性差。因此采用异常处理机制。



> Java异常处理

Java采用的异常处理机制，是将异常处理的程序代码集中在一起，与正常的程序代码分开，使得程序简洁、优雅，并易于维护。

Java异常处理的方式：

- try-catch-finally
- throws + 异常类型

> 概念

Java提供的是异常处理的**抓抛模型**。

**“抛”**：Java程序的执行过程中如出现异常，会生成一个**异常类对象**，该异常对象将被提交给Java运行时系统，这个过程称为**抛出(throw)异常。**

一旦抛出异常对象以后，其后的代码就不再执行。



“**抓**”：如果一个方法内抛出异常，该异常对象会被抛给调用者方法中处理。如果异常没有在调用者方法中处理，它继续被抛给这个调用方法的上层方法。这个过程将一直继续下去，直到异常被处理。这一过程称为**捕获(`catch`)异常**。



> 异常对象的生成

- 由虚拟机自动生成：程序运行过程中，虚拟机检测到程序发生了问题，如果在当前代码中没有找到相应的处理程序，就会在后台自动创建一个对应异常类的实例对象并抛出——自动抛出
- 由开发人员手动创建：Exception exception= new ClassCastException();——创建好的异常对象不抛出对程序没有任何影响，和创建一个普通对象一样。



> 异常的抛出机制

![image-20201216213717039](https://raw.githubusercontent.com/SaulJWu/images/main/20201216213717.png)

- 如果一个方法内抛出异常，该异常对象会被抛给调用者方法中处理。如果异常没有在调用者方法中处理，它继续被抛给这个调用方法的上层方法。这个过程将一直继续下去，直到异常被处理。这一过程称为**捕获(`catch`)异常**。
- 如果一个异常回到main()方法，并且main()也不处理，则程序运行终止。
- 程序员通常只能处理Exception，而对Error无能为力。



## try-catch-finally

异常处理是通过`try-catch-finally`语句实现的。

使用`try-catch-finally`处理编译时异常，使得程序在编译时不再报错，但是运行时扔可能报错。相当于使用`try-catch-finally`将一个编译时可能出现的异常，延迟到运行时出现。

> 语法格式：

```java
try{
	......//可能产生异常的代码
}catch(ExceptionName1e){
	......//当产生ExceptionName1型异常时的处置措施
}catch(ExceptionName2e){
......//当产生ExceptionName2型异常时的处置措施
}[finally{
......//无论是否发生异常，都无条件执行的语句
}]
```

- try
  - 捕获异常的第一步是用try{...}语句块选定捕获异常的范围，将可能出现异常的代码放在try语句块中。
  - 使用try将可能出现异常代码包装起来，在执行过程中，一旦出现异常，就会生成一个对应异常类的对象，根据此对象的类型，去catch中匹配。
- catch(Exceptiontypee)
  - 在catch语句块中是对异常对象进行处理的代码。每个try语句块可以伴随一个或多个catch语句，用于处理可能产生的不同类型的异常对象。
  - 一旦try的异常对象匹配到某一个catch时，进入catch中进行异常的处理。一旦处理完成，就跳出当前的try-catch结构（在没有些finally的情况下），继续执行其后的代码。
  - catch中的异常类型如果没有子父类关系，顺序无所谓。
  - 如果捕捉的异常类型满足子父类关系，子类一定要声明在父类的上面，否则，编译报错。
- `finally`
  - 是可选的。不一定要写。

- `try-catch-finally`可以嵌套使用。



> 如果明确知道产生的是何种异常，可以用该异常类作为catch的参数；也可以用其父类作为catch的参数。

比如：可以用ArithmeticException类作为参数的地方，就可以用RuntimeException类作为参数，或者用所有异常的父类Exception类作为参数。但不能是与ArithmeticException类无关的异常，如NullPointerException（catch中的语句将不会执行）。



> 捕获异常的有关信息：

与其它对象一样，可以访问一个异常对象的成员变量或调用它的方法。

- getMessage() 获取异常信息，返回字符串
- printStackTrace()  获取异常类名和异常信息，以及异常出现在程序中的位置。返回值void。



> finally

- 捕获异常的最后一步是通过finally语句为异常处理提供一个统一的出口，使得在控制流转到程序的其它部分以前，能够对程序的状态作统一的管理。
- **不论在try代码块中是否发生了异常事件，catch语句是否执行，catch语句是否有异常，catch语句中是否有return，finally块中的语句都会被执行。**

- finally语句和catch语句是任选的。



像数据库连接、输入输出流、网络编程Socket等资源，JVM是不能自动回收的，我们需要自己手动的进行资源的释放。此时的资源释放，就需要声明在finally中。



> 捕获和不捕获异常，程序的运行有什么不同

- 前面使用的异常都是`RuntimeException`类或是它的子类，这些类的异常的特点是：即使没有使用try和catch捕获，Java自己也能捕获，并且编译通过( 但运行时会发生异常使得程序运行终止)。
- 如果抛出的异常是`IOException`等类型的非运行时异常，则必须捕获，否则编译错误。也就是说，我们必须处理编译时异常，将异常进行捕捉，转化为运行时异常



## throws

> 声明抛出异常是Java中处理异常的第二种方式

- 如果一个方法(中的语句执行时)可能生成某种异常，但是并不能确定如何处理这种异常，则此方法应**显示地**声明抛出异常，表明该方法将不对这些异常进行处理，而由该方法的**调用者**负责处理。
- 在方法声明中用`throws`语句可以声明抛出异常的列表，`throws`后面的异常类型可以是方法中产生的异常类型，也可以是它的父类。



> 声明抛出异常举例：

~~~java
public void readFile(Stringfile) throws FileNotFoundException{
    ......
 //读文件的操作可能产生FileNotFoundException类型的异常
 FileInputStreamfis=newFileInputStream(file);
    ........
}
~~~



> 重写方法声明抛出异常的原则

**重写方法不能抛出比被重写方法范围更大的异常类型。**

在多态的情况下，对`methodA()`方法的调用-异常的捕获按父类声明的异常处理。

~~~java
public class A {
    public void methodA() throws IOException{
    ......
	}  
}

public class B1 extends A {
    public void methodA() throws FileNotFoundException{
        ......
    }  
}

public class B2 extends A {
    public void methodA() throws Exception{   //报错
    ......
	}
}
~~~



> 体会

- `try-catch-finally`：真正的将异常给处理掉了。
- `throws`的方式只是将异常抛给了方法的调用者，并没有真正将异常处理掉。



> 开发中如何选择哪种异常处理？

- 如果父类中被重写的方法没有`throws`方式处理异常，则子类重写的方法也不能使用`throws`，意味着如果子类重写的方法中有异常，必须使用`try-catch-finally`方式处理。
- 执行的方法中，先后又调用了另外的几个方法，这几个方法是递进关系执行的，建议这几个方法使用throws的方式进行处理。而第一个执行的方法可以考虑使用`try-catch-finally`方式处理。





## `throw`手动抛出异常

> `Java`异常类对象除在程序执行过程中出现异常时由系统自动生成并抛出，**也可根据需要使用人工创建并抛出**。

首先要生成异常类对象，然后通过`throw`语句实现**手动抛出操作**(提交给Java运行环境)。

~~~java
IOException e = new IOException();
throw e;
~~~

**可以抛出的异常必须是`Throwable`或其子类的实例。**

下面的语句在编译时将会产生语法错误：

```java
throw new String("wanttothrow");
```



## 自定义异常类

- 一般地，用户自定义异常类都是`RuntimeException`的子类。
- 自定义异常类通常需要编写几个**重载的构造器**。
- 自定义异常需要提供`serialVersionUID`
- 自定义的异常通过`throw`抛出。
- 自定义异常最重要的是异常类的名字，当异常出现时，可以根据名字判断异常类型。



> 用户自定义异常类MyException，用于描述数据取值范围错误信息。用户自己的异常类必须继承现有的异常类。

~~~java
class MyException extends Exception {
    
    static final long serialVersionUID = 13465653435L;
    
    private int idnumber;
    
    public MyException(String message, intid) {
        super(message);
        this.idnumber= id;
    }
    
    public int getId() {
        returnidnumber;
    }
}
~~~

~~~java
public class MyExpTest {
    
    public void regist(intnum) throws MyException {
        if(num< 0)
            thrownew MyException("人数为负值，不合理", 3);
        else
            System.out.println("登记人数"+ num);
    }
    
    public void manager() {
        try{
            regist(100);
        } catch(MyException e) {
            System.out.print("登记失败，出错种类"+ e.getId());
        }
        System.out.print("本次登记操作结束");
    }
    
    public static void main(String args[]) {
        MyExpTest t= new MyExpTest();
        t.manager();
    }
}
~~~



## 总结

![image-20201216223707815](https://raw.githubusercontent.com/SaulJWu/images/main/20201216223707.png)



## 一首小悟结束异常处理

世界上最遥远的**距离**，是我在`if`里你在`else`里，似乎一直相伴又永远分离；

世界上最痴心的**等待**，是我当`case`你是`switch`，或许永远都选不上自己；

世界上最真情的**相依**，是你在`try`我在`catch`。无论你发神马脾气，我都默默承受，静静处理。到那时，再来期待我们的`finally`。